package com.nisecoder.gradle.plugin.github.env


enum class GithubActionsEnv {
    CI,
    GITHUB_WORKFLOW,
    GITHUB_RUN_ID,
    GITHUB_RUN_NUMBER,
    GITHUB_JOB,
    GITHUB_ACTION,
    GITHUB_ACTION_PATH,
    GITHUB_ACTIONS,
    GITHUB_ACTOR,
    GITHUB_REPOSITORY,
    GITHUB_EVENT_NAME,
    GITHUB_EVENT_PATH,
    GITHUB_WORKSPACE,
    GITHUB_SHA,
    GITHUB_REF,
    GITHUB_HEAD_REF,
    GITHUB_BASE_REF,
    GITHUB_SERVER_URL,
    GITHUB_API_URL,
    GITHUB_GRAPHQL_URL,
    RUNNER_NAME,
    RUNNER_OS,
    RUNNER_TEMP,
    RUNNER_TOOL_CACHE,
}
