name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: gradle/actions/setup-gradle@v321
        with:
          gradle-version: wrapper
          arguments: build
