name: "Publish Artifacts"

on:
  push:
    tags: [ "v*" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Java for Publishing
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4
      - name: Publish to Github Packages
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_publishVersion: ${{ github.ref }}
          ORG_GRADLE_PROJECT_GitHubUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_GitHubPassword: ${{ secrets.GITHUB_TOKEN }}