name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # use gradle runtime's java language version to build each gradle-plugins version
        java-version:
          - 17
          - 21
          # - 22 # not supported on setup-java

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew build
      - uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'